


import connexion.ConnexionOracleFactory;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rémy
 */
public class FenetrePouleLE extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public FenetrePouleLE() {
        initComponents();
        listModelPouleA = new javax.swing.DefaultListModel<>();
        listePouleA.setModel(listModelPouleA);
        listModelPouleB = new javax.swing.DefaultListModel<>();
        listePouleB.setModel(listModelPouleB);
        listModelPouleC = new javax.swing.DefaultListModel<>();
        listePouleC.setModel(listModelPouleC);
        listModelPouleD = new javax.swing.DefaultListModel<>();
        listePouleD.setModel(listModelPouleD);
        listModelPouleE = new javax.swing.DefaultListModel<>();
        listePouleE.setModel(listModelPouleE);
        listModelPouleF = new javax.swing.DefaultListModel<>();
        listePouleF.setModel(listModelPouleF);
        listModelPouleG = new javax.swing.DefaultListModel<>();
        listePouleG.setModel(listModelPouleG);
        listModelPouleH = new javax.swing.DefaultListModel<>();
        listePouleH.setModel(listModelPouleH);
        listModelPouleI = new javax.swing.DefaultListModel<>();
        listePouleI.setModel(listModelPouleI);
        listModelPouleJ = new javax.swing.DefaultListModel<>();
        listePouleJ.setModel(listModelPouleJ);
        listModelPouleK = new javax.swing.DefaultListModel<>();
        listePouleK.setModel(listModelPouleK);
        listModelPouleL = new javax.swing.DefaultListModel<>();
        listePouleL.setModel(listModelPouleL);
        
        consultationPoule(listModelPouleA, "A");
        consultationPoule(listModelPouleB, "B");
        consultationPoule(listModelPouleC, "C");
        consultationPoule(listModelPouleD, "D");
        consultationPoule(listModelPouleE, "E");
        consultationPoule(listModelPouleF, "F");
        consultationPoule(listModelPouleG, "G");
        consultationPoule(listModelPouleH, "H");
        consultationPoule(listModelPouleI, "I");
        consultationPoule(listModelPouleJ, "J");
        consultationPoule(listModelPouleK, "K");
        consultationPoule(listModelPouleL, "L");
    }
    
    
    
    

    // Ouvre une connexion stockée dans la variable connexion
    public void openConnection(javax.swing.DefaultListModel<String> listModel) {
        connexion = ConnexionOracleFactory.creerConnexion();
        if (connexion == null) {
            listModel.addElement("Probleme de connection.");
            System.exit(1);
        }
    }

    public void closeConnection() {
        try {
            connexion.close();	// Fermeture de la connexion
        } catch (java.sql.SQLException e) {
            System.out.println("ERREUR ORACLE" + e.getMessage());
        }
    }

    
    private void consultationPoule(javax.swing.DefaultListModel<String> listModel, String nomPoule) {
        //liste des attributs récupérés de la BDD:
        String nomClub;
        int nbPoints;
        
        //gestion des buts pour les coupes européennes?
        int nbButsMis;
        int nbButsPris;

        listModel.clear();      //listModel.removeAllElements();
        
        //FINIR LA REQUETE DES ELEMENTS !!
        try {
            openConnection(listModel);
            java.sql.Statement requete;
            requete = connexion.createStatement();
            java.sql.ResultSet query;
            query = requete.executeQuery(
                    "SELECT nomclub, ptseurope FROM club WHERE nompoule = '"+nomPoule+"' AND le = 1 ORDER BY ptseurope DESC");//gérer nbpointsldc
            while (query.next()) {
                nomClub = query.getString(1);
                nbPoints = query.getInt(2);

                listModel.addElement(nomClub
                        + "    "
                        + nbPoints);
            }
            query.close();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException e) {
            listModel.addElement("Erreur execution requete " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retour = new javax.swing.JLabel();
        pouleE = new javax.swing.JScrollPane();
        listePouleE = new javax.swing.JList();
        pouleC = new javax.swing.JScrollPane();
        listePouleC = new javax.swing.JList();
        pouleB = new javax.swing.JScrollPane();
        listePouleB = new javax.swing.JList();
        pouleA = new javax.swing.JScrollPane();
        listePouleA = new javax.swing.JList();
        pouleG = new javax.swing.JScrollPane();
        listePouleG = new javax.swing.JList();
        pouleD = new javax.swing.JScrollPane();
        listePouleD = new javax.swing.JList();
        pouleL = new javax.swing.JScrollPane();
        listePouleL = new javax.swing.JList();
        pouleI = new javax.swing.JScrollPane();
        listePouleI = new javax.swing.JList();
        pouleH = new javax.swing.JScrollPane();
        listePouleH = new javax.swing.JList();
        pouleK = new javax.swing.JScrollPane();
        listePouleK = new javax.swing.JList();
        pouleJ = new javax.swing.JScrollPane();
        listePouleJ = new javax.swing.JList();
        pouleF = new javax.swing.JScrollPane();
        listePouleF = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        phaseFinaleButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 533));
        getContentPane().setLayout(null);

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fleche-retour.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(910, 400, 70, 70);

        listePouleE.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleE.setViewportView(listePouleE);

        getContentPane().add(pouleE);
        pouleE.setBounds(690, 80, 140, 120);

        listePouleC.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleC.setViewportView(listePouleC);

        getContentPane().add(pouleC);
        pouleC.setBounds(350, 80, 140, 120);

        listePouleB.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleB.setViewportView(listePouleB);

        getContentPane().add(pouleB);
        pouleB.setBounds(190, 80, 140, 120);

        listePouleA.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleA.setViewportView(listePouleA);

        getContentPane().add(pouleA);
        pouleA.setBounds(40, 80, 130, 120);

        listePouleG.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleG.setViewportView(listePouleG);

        getContentPane().add(pouleG);
        pouleG.setBounds(40, 260, 130, 120);

        listePouleD.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleD.setViewportView(listePouleD);

        getContentPane().add(pouleD);
        pouleD.setBounds(520, 80, 150, 120);

        listePouleL.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleL.setViewportView(listePouleL);

        getContentPane().add(pouleL);
        pouleL.setBounds(850, 260, 140, 120);

        listePouleI.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleI.setViewportView(listePouleI);

        getContentPane().add(pouleI);
        pouleI.setBounds(350, 260, 140, 120);

        listePouleH.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleH.setViewportView(listePouleH);

        getContentPane().add(pouleH);
        pouleH.setBounds(190, 260, 140, 120);

        listePouleK.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleK.setViewportView(listePouleK);

        getContentPane().add(pouleK);
        pouleK.setBounds(690, 260, 140, 120);

        listePouleJ.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleJ.setViewportView(listePouleJ);

        getContentPane().add(pouleJ);
        pouleJ.setBounds(520, 260, 150, 120);

        listePouleF.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        pouleF.setViewportView(listePouleF);

        getContentPane().add(pouleF);
        pouleF.setBounds(850, 80, 140, 120);

        jLabel1.setText("Poule A");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 210, 80, 14);

        jLabel12.setText("Poule B");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(220, 210, 70, 14);

        jLabel13.setText("Poule C");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 210, 70, 14);

        jLabel14.setText("Poule D");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(550, 210, 70, 14);

        jLabel15.setText("Poule E");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(720, 210, 70, 14);

        jLabel16.setText("Poule F");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(880, 210, 70, 14);

        jLabel17.setText("Poule G");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(70, 390, 80, 14);

        jLabel18.setText("Poule H");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(220, 390, 70, 14);

        jLabel19.setText("Poule I");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(380, 390, 80, 14);

        jLabel20.setText("Poule J");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(550, 390, 90, 14);

        jLabel21.setText("Poule K");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(720, 390, 100, 14);

        jLabel22.setText("Poule L");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(880, 390, 70, 14);

        phaseFinaleButton.setText("Phase finale");
        phaseFinaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phaseFinaleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(phaseFinaleButton);
        phaseFinaleButton.setBounds(390, 440, 190, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 506);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
        
        this.setVisible(false);
    }//GEN-LAST:event_retourMouseClicked

    private void retourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMouseExited

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMousePressed

    private void phaseFinaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phaseFinaleButtonActionPerformed
        FenetrePhaseFinaleLE phaseFinale;
        phaseFinale = new FenetrePhaseFinaleLE();
        phaseFinale.setVisible(true);
    }//GEN-LAST:event_phaseFinaleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test2().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JList listePouleA;
    private javax.swing.JList listePouleB;
    private javax.swing.JList listePouleC;
    private javax.swing.JList listePouleD;
    private javax.swing.JList listePouleE;
    private javax.swing.JList listePouleF;
    private javax.swing.JList listePouleG;
    private javax.swing.JList listePouleH;
    private javax.swing.JList listePouleI;
    private javax.swing.JList listePouleJ;
    private javax.swing.JList listePouleK;
    private javax.swing.JList listePouleL;
    private javax.swing.JButton phaseFinaleButton;
    private javax.swing.JScrollPane pouleA;
    private javax.swing.JScrollPane pouleB;
    private javax.swing.JScrollPane pouleC;
    private javax.swing.JScrollPane pouleD;
    private javax.swing.JScrollPane pouleE;
    private javax.swing.JScrollPane pouleF;
    private javax.swing.JScrollPane pouleG;
    private javax.swing.JScrollPane pouleH;
    private javax.swing.JScrollPane pouleI;
    private javax.swing.JScrollPane pouleJ;
    private javax.swing.JScrollPane pouleK;
    private javax.swing.JScrollPane pouleL;
    private javax.swing.JLabel retour;
    // End of variables declaration//GEN-END:variables
    private static javax.swing.DefaultListModel<String> listModelPouleA;
    private static javax.swing.DefaultListModel<String> listModelPouleB;
    private static javax.swing.DefaultListModel<String> listModelPouleC;
    private static javax.swing.DefaultListModel<String> listModelPouleD;
    private static javax.swing.DefaultListModel<String> listModelPouleE;
    private static javax.swing.DefaultListModel<String> listModelPouleF;
    private static javax.swing.DefaultListModel<String> listModelPouleG;
    private static javax.swing.DefaultListModel<String> listModelPouleH;
    private static javax.swing.DefaultListModel<String> listModelPouleI;
    private static javax.swing.DefaultListModel<String> listModelPouleJ;
    private static javax.swing.DefaultListModel<String> listModelPouleK;
    private static javax.swing.DefaultListModel<String> listModelPouleL;
    private java.sql.Connection connexion;
}
