
import connexion.ConnexionOracleFactory;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rémy
 */
public class FenetreChampionnat extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    
    public FenetreChampionnat(String nomDivision) {
        this.nomDivision = nomDivision;
        initComponents();
        listModel = new javax.swing.DefaultListModel<>();
        jList1.setModel(listModel);

        consultationDivision(nomDivision);
        //listModel.addElement(FenetreChampionnat.nomDivision);
    }

    // Ouvre une connexion stockée dans la variable connexion
    public void openConnection() {
        connexion = ConnexionOracleFactory.creerConnexion();
        if (connexion == null) {
            listModel.addElement("Probleme de connection.");
            System.exit(1);
        }
    }

    public void closeConnection() {
        try {
            connexion.close();	// Fermeture de la connexion
        } catch (java.sql.SQLException e) {
            System.out.println("ERREUR ORACLE" + e.getMessage());
        }
    }

    
    private void consultationDivision(String nomDivision) {
        //liste des attributs récupérés de la BDD:
        String nomClub;
        int nbPoints;
        int nbButsMis;
        int nbButsPris;
        int journée;//dans la base de données?

        listModel.clear();      //listModel.removeAllElements();
        
        //FINIR LA REQUETE DES ELEMENTS !!
        try {
            openConnection();
            java.sql.Statement requete;
            requete = connexion.createStatement();
            java.sql.ResultSet query;
            query = requete.executeQuery(
                    "SELECT nomclub, ptschamp, butchamp FROM club WHERE division = '"+nomDivision+"' ORDER BY ptschamp desc, butchamp DESC" );
            while (query.next()) {
                nomClub = query.getString(1)+"    "+query.getInt(2)+"    "+query.getInt(3);

                listModel.addElement(nomClub);
            }
            query.close();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException e) {
            listModel.addElement("Erreur execution requete " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retour = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        calendrierButton = new javax.swing.JButton();
        raffraichir = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 533));
        getContentPane().setLayout(null);

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fleche-retour.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(910, 400, 70, 70);

        jLabel1.setText("Classement :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 200, 100, 20);

        jList1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 260, 550, 210);

        jLabel2.setText("Nom                       Nb Points                Journée                      Classement");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 240, 390, 14);

        calendrierButton.setText("Calendrier");
        calendrierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendrierButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calendrierButton);
        calendrierButton.setBounds(660, 160, 110, 50);

        raffraichir.setText("Rafraichir");
        raffraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raffraichirActionPerformed(evt);
            }
        });
        getContentPane().add(raffraichir);
        raffraichir.setBounds(140, 330, 120, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 506);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
        
        this.setVisible(false);
    }//GEN-LAST:event_retourMouseClicked

    private void retourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMouseExited

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMousePressed

    private void calendrierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendrierButtonActionPerformed
        GenererCalendrier calendrier;
        calendrier = new GenererCalendrier(nomDivision);
        calendrier.setVisible(true);
    }//GEN-LAST:event_calendrierButtonActionPerformed

    private void raffraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raffraichirActionPerformed
        consultationDivision(this.nomDivision);
    }//GEN-LAST:event_raffraichirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreChampionnat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreChampionnat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreChampionnat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreChampionnat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreChampionnat().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton calendrierButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton raffraichir;
    private javax.swing.JLabel retour;
    // End of variables declaration//GEN-END:variables
    private static String nomDivision;
    private static javax.swing.DefaultListModel<String> listModel;
    private java.sql.Connection connexion;
}
