


import connexion.ConnexionOracleFactory;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rémy
 */
public class FenetreAdminToursSupprimer extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public FenetreAdminToursSupprimer() {
        initComponents();
        afficheCoupe();
        affichePays();
        afficheTours();
    }

    private void afficheCoupe() {
        nomCoupeBox.addItem("CN");
        nomCoupeBox.addItem("LDC");
        nomCoupeBox.addItem("LE");
        nomCoupeBox.setSelectedIndex(0);
    }
    
    private void afficheTours()
    {
        tourDeCoupeBox.addItem("Finale");
        tourDeCoupeBox.addItem("Demies");
        tourDeCoupeBox.addItem("Quarts");
        tourDeCoupeBox.addItem("Huitièmes");
        tourDeCoupeBox.addItem("Seizièmes");
        tourDeCoupeBox.addItem("Trentesdeuxièmes");
        tourDeCoupeBox.addItem("Tour Préliminaire");
    }

    private void affichePays() {
        paysBox.addItem("France");
        paysBox.addItem("Italie");
        paysBox.addItem("Espagne");
        paysBox.addItem("Pays-Bas");
        paysBox.addItem("Allemagne");
        paysBox.addItem("Angleterre");
        paysBox.addItem("Russie");
        paysBox.addItem("Portugal");
        paysBox.addItem("Europe");
        paysBox.setSelectedIndex(0);
    }

    // Ouvre une connexion stockée dans la variable connexion
    public void openConnection() {
        connexion = ConnexionOracleFactory.creerConnexion();
        if (connexion == null) {
            System.exit(1);
        }
    }

    public void closeConnection() {
        try {
            connexion.close();	// Fermeture de la connexion
        } catch (java.sql.SQLException e) {
            System.out.println("ERREUR ORACLE" + e.getMessage());
        }
    }

    

    private void consultationClubPaysTours(String nomPays) {
        //liste des attributs récupérés de la BDD:
        String nomClubs;
        //String nomClub2;
        
        double tour;

        try {
            openConnection();
            java.sql.Statement requete;
            requete = connexion.createStatement();
            java.sql.ResultSet query;

            
            switch(tourDeCoupeBox.getSelectedItem().toString())
            {
                case "Finale":
                    tour = 1000;
                    break;
                case "Demies":
                    tour = 0.5;
                    break;
                case "Quarts":
                    tour = 0.25;
                    break;
                case "Huitièmes":
                    tour = 0.125;
                    break;
                case "Seizièmes":
                    tour = 0.0625;
                    break;
                case "Trentesdeuxièmes":
                    tour = 0.03125;
                    break;
                default :
                    tour = 0;
                    break;
            }
            
            
            if(nomPays.equalsIgnoreCase("Europe"))
            {
                query = requete.executeQuery(
                    "SELECT DISTINCT nomclub1, nomclub2 FROM matchfootball WHERE nom_competition = '"+nomCoupeBox.getSelectedItem().toString()+"' AND no_journee = "+tour+" ORDER BY nomclub1 ASC");
            }
            else
            {/////////////////////////////////////////////recuperer nom compet en fct du pays
                query = requete.executeQuery(
                 "SELECT DISTINCT nomclub1, nomclub2 FROM matchfootball WHERE nom_competition = 'coupe" + nomPays + "' AND no_journee = "+tour+" ORDER BY nomclub ASC"); 
            }
            
            while (query.next()) {
                nomClubs = query.getString(1)+" "+query.getString(2);
                //nomClub2 = query.getString(1);

                nomDeuxClubsBox.addItem(nomClubs);
                //club2Box.addItem(nomClub2);
            }

            nomDeuxClubsBox.setSelectedIndex(0);
            query.close();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retour = new javax.swing.JLabel();
        tourDeCoupeBox = new javax.swing.JComboBox();
        nomDeuxClubsBox = new javax.swing.JComboBox();
        supprimerConfrontationButton = new javax.swing.JButton();
        nomCoupeBox = new javax.swing.JComboBox();
        paysBox = new javax.swing.JComboBox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 533));
        getContentPane().setLayout(null);

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fleche-retour.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(910, 400, 70, 70);

        tourDeCoupeBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tourDeCoupeBoxmodifTour(evt);
            }
        });
        getContentPane().add(tourDeCoupeBox);
        tourDeCoupeBox.setBounds(420, 270, 210, 40);

        nomDeuxClubsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomDeuxClubsBoxActionPerformed(evt);
            }
        });
        getContentPane().add(nomDeuxClubsBox);
        nomDeuxClubsBox.setBounds(650, 270, 220, 40);

        supprimerConfrontationButton.setText("Supprimer");
        supprimerConfrontationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerConfrontationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(supprimerConfrontationButton);
        supprimerConfrontationButton.setBounds(410, 420, 150, 40);

        nomCoupeBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nomCoupeBoxmodifCoupe(evt);
            }
        });
        getContentPane().add(nomCoupeBox);
        nomCoupeBox.setBounds(260, 270, 140, 40);

        paysBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paysBoxmodifierPays(evt);
            }
        });
        getContentPane().add(paysBox);
        paysBox.setBounds(110, 270, 130, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 506);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
        
        this.setVisible(false);
    }//GEN-LAST:event_retourMouseClicked

    private void retourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMouseExited

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMousePressed

    private void tourDeCoupeBoxmodifTour(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tourDeCoupeBoxmodifTour
        consultationClubPaysTours(paysBox.getSelectedItem().toString());
    }//GEN-LAST:event_tourDeCoupeBoxmodifTour

    private void supprimerConfrontationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerConfrontationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerConfrontationButtonActionPerformed

    private void nomCoupeBoxmodifCoupe(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nomCoupeBoxmodifCoupe
        try{
            paysBox.removeAllItems();
            nomDeuxClubsBox.removeAllItems();
            if(nomCoupeBox.getSelectedItem().toString().equalsIgnoreCase("CN"))
            {
                paysBox.addItem("France");
                paysBox.addItem("Italie");
                paysBox.addItem("Espagne");
                paysBox.addItem("Pays-Bas");
                paysBox.addItem("Allemagne");
                paysBox.addItem("Angleterre");
                paysBox.addItem("Russie");
                paysBox.addItem("Portugal");
                paysBox.setSelectedIndex(0);
                consultationClubPaysTours(paysBox.getSelectedItem().toString());

                if(!paysBox.isEnabled()) paysBox.setEnabled(true);
            }
            else
            {
                paysBox.addItem("Europe");
                consultationClubPaysTours(paysBox.getSelectedItem().toString());

                paysBox.setEnabled(false);
            }
        }
        catch(Exception e)
        {
            //System.out.println("erreur modifCoupe : "+e);
        }
    }//GEN-LAST:event_nomCoupeBoxmodifCoupe

    private void paysBoxmodifierPays(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paysBoxmodifierPays
        try{
            nomDeuxClubsBox.removeAllItems();
            consultationClubPaysTours(paysBox.getSelectedItem().toString());
        }
        catch(Exception e)
        {
            //System.out.println("erreur modifierPays : "+e);
        }
    }//GEN-LAST:event_paysBoxmodifierPays

    private void nomDeuxClubsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomDeuxClubsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomDeuxClubsBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test2().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JComboBox nomCoupeBox;
    private javax.swing.JComboBox nomDeuxClubsBox;
    private javax.swing.JComboBox paysBox;
    private javax.swing.JLabel retour;
    private javax.swing.JButton supprimerConfrontationButton;
    private javax.swing.JComboBox tourDeCoupeBox;
    // End of variables declaration//GEN-END:variables
    private java.sql.Connection connexion;
}
