


import connexion.ConnexionOracleFactory;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rémy
 */
public class FenetreAdminPoulesAjouter extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public FenetreAdminPoulesAjouter() {
        initComponents();
        afficheCoupe();
        affichePays();
    }

    // Ouvre une connexion stockée dans la variable connexion
    public void openConnection() {
        connexion = ConnexionOracleFactory.creerConnexion();
        if (connexion == null) {
            System.exit(1);
        }
    }

    public void closeConnection() {
        try {
            connexion.close();	// Fermeture de la connexion
        } catch (java.sql.SQLException e) {
            System.out.println("ERREUR ORACLE" + e.getMessage());
        }
    }

    private void choisirNomPoule(String nomCompetiton) {
        if (nomCompetiton.equalsIgnoreCase("ldc")) {
            nomPouleBox.addItem("A");
            nomPouleBox.addItem("B");
            nomPouleBox.addItem("C");
            nomPouleBox.addItem("D");
            nomPouleBox.addItem("E");
            nomPouleBox.addItem("F");
            nomPouleBox.addItem("G");
            nomPouleBox.addItem("H");
        } else {
            nomPouleBox.addItem("A");
            nomPouleBox.addItem("B");
            nomPouleBox.addItem("C");
            nomPouleBox.addItem("D");
            nomPouleBox.addItem("E");
            nomPouleBox.addItem("F");
            nomPouleBox.addItem("G");
            nomPouleBox.addItem("H");
            nomPouleBox.addItem("I");
            nomPouleBox.addItem("J");
            nomPouleBox.addItem("K");
            nomPouleBox.addItem("L");
        }
    }

    private void afficheCoupe() {
        nomCoupeBox.addItem("LDC");
        nomCoupeBox.addItem("LE");
        nomCoupeBox.setSelectedIndex(0);
    }

    private void affichePays() {
        nomPaysClubBox.addItem("France");
        nomPaysClubBox.addItem("Italie");
        nomPaysClubBox.addItem("Espagne");
        nomPaysClubBox.addItem("Pays-Bas");
        nomPaysClubBox.addItem("Allemagne");
        nomPaysClubBox.addItem("Angleterre");
        nomPaysClubBox.addItem("Russie");
        nomPaysClubBox.addItem("Portugal");
        nomPaysClubBox.addItem("Europe");
        nomPaysClubBox.setSelectedIndex(0);
    }

    private void consultationClub(String nomPays, String nomCompetition) {
        //liste des attributs récupérés de la BDD:
        String nomClub;

        try {
            openConnection();
            java.sql.Statement requete;
            requete = connexion.createStatement();
            java.sql.ResultSet query;

            if(nomCompetition.equalsIgnoreCase("ldc"))
            {
                query = requete.executeQuery(
                    "SELECT DISTINCT nomclub FROM club WHERE nompays = '" + nomPays + "' AND ldc = 1 AND nompoule is null ORDER BY nomclub ASC");
            }
            else
            {
                query = requete.executeQuery(
                    "SELECT DISTINCT nomclub FROM club WHERE nompays = '" + nomPays + "' AND le = 1 AND nompoule is null ORDER BY nomclub ASC");                
            }
            
            
            while (query.next()) {
                nomClub = query.getString(1);

                nomClubBox.addItem(nomClub);
            }

            //nomClubBox.setSelectedIndex(0);
            query.close();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retour = new javax.swing.JLabel();
        nomPouleBox = new javax.swing.JComboBox();
        nomPaysClubBox = new javax.swing.JComboBox();
        ajouterClubPouleButton = new javax.swing.JButton();
        nomCoupeBox = new javax.swing.JComboBox();
        nomClubBox = new javax.swing.JComboBox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 533));
        getContentPane().setLayout(null);

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fleche-retour.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                retourMousePressed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(910, 400, 70, 70);

        nomPouleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomPouleBoxActionPerformed(evt);
            }
        });
        getContentPane().add(nomPouleBox);
        nomPouleBox.setBounds(490, 250, 180, 30);

        nomPaysClubBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nomPaysClubBoxchoixPays(evt);
            }
        });
        getContentPane().add(nomPaysClubBox);
        nomPaysClubBox.setBounds(300, 330, 130, 30);

        ajouterClubPouleButton.setText("Ajouter");
        ajouterClubPouleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterClubPouleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ajouterClubPouleButton);
        ajouterClubPouleButton.setBounds(410, 380, 100, 40);

        nomCoupeBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nomCoupeBoxchoiriCompetition(evt);
                nomCoupeBoxmodifierClubs(evt);
            }
        });
        getContentPane().add(nomCoupeBox);
        nomCoupeBox.setBounds(300, 250, 130, 30);
        getContentPane().add(nomClubBox);
        nomClubBox.setBounds(490, 330, 180, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1000, 506);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
        
        this.setVisible(false);
    }//GEN-LAST:event_retourMouseClicked

    private void retourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseExited
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMouseExited

    private void retourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMousePressed
        ImageIcon i = new ImageIcon(getClass().getResource("/Images/fleche-retour_p.png"));
        retour.setIcon(i);
    }//GEN-LAST:event_retourMousePressed

    private void nomPaysClubBoxchoixPays(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nomPaysClubBoxchoixPays
        nomClubBox.removeAllItems();
        consultationClub(nomPaysClubBox.getSelectedItem().toString(), nomCoupeBox.getSelectedItem().toString());
    }//GEN-LAST:event_nomPaysClubBoxchoixPays

    private void ajouterClubPouleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterClubPouleButtonActionPerformed
        //liste des attributs récupérés de la BDD:
        String nomClub;

        try {
            openConnection();
            java.sql.PreparedStatement  requete;
            requete = connexion.prepareStatement (
                "UPDATE club SET nompoule = '"+nomPouleBox.getSelectedItem().toString()+"' WHERE nomclub = '"+nomClubBox.getSelectedItem().toString()+"'");

            requete.executeQuery();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException e) {

        }
    }//GEN-LAST:event_ajouterClubPouleButtonActionPerformed

    private void nomCoupeBoxchoiriCompetition(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nomCoupeBoxchoiriCompetition
        nomPouleBox.removeAllItems();
        choisirNomPoule(nomCoupeBox.getSelectedItem().toString());
    }//GEN-LAST:event_nomCoupeBoxchoiriCompetition

    private void nomCoupeBoxmodifierClubs(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nomCoupeBoxmodifierClubs
        nomClubBox.removeAllItems();////////////////////////////////////////////////////!!!!!!!!!!!!!!faire !!!!
        try
        {
            consultationClub(nomPaysClubBox.getSelectedItem().toString(), nomCoupeBox.getSelectedItem().toString());
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_nomCoupeBoxmodifierClubs

    private void nomPouleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomPouleBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomPouleBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test2().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterClubPouleButton;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox nomClubBox;
    private javax.swing.JComboBox nomCoupeBox;
    private javax.swing.JComboBox nomPaysClubBox;
    private javax.swing.JComboBox nomPouleBox;
    private javax.swing.JLabel retour;
    // End of variables declaration//GEN-END:variables
    private java.sql.Connection connexion;
}
